AllCops:
  NewCops: disable
  SuggestExtensions: false

Bundler/OrderedGems:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/jekyll-activitypub-static.rb

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
