title: "Jekyll ActivityPub Static Plugin Test Site"
description: "A demo site to test the jekyll-activitypub-static plugin"
url: "http://localhost:4000"
author: "evan"

plugins:
  - jekyll-activitypub-static

include:
  - activitypub
  - .well-known

keep_files:
  - actor.jsonld
  - activitypub
  - .well-known

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
